# Use the official Node.js image as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json into the container
COPY ./frontend/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code into the container
COPY ./frontend .

# Build the React app
RUN npm run build

# Use the official Nginx image to serve the build files
FROM nginx:alpine

# Copy the build files from the previous stage into the Nginx web directory
COPY --from=0 /app/build /usr/share/nginx/html

# Expose the port Nginx runs on
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
